




# --------------------------
# ICMP TYPES
DESTINATION_UNREACHABLE = 3
TIME_EXCEEDED = 11
ECHO_REQUEST = 8
ECHO_REPLY = 0
# --------------------------

# --------------------------
# ICMP CODES
# DESTINATION_UNREACHABLE CODES:
NET_UNREACHABLE = 0
HOST_UNREACHABLE = 1
PROTOCOL_UNREACHABLE = 2
PORT_UNREACHABLE = 3
FRAGMENTATION_NEEDED_AND_DF_SET = 4
SOURCE_ROUTE_FAILED = 5
# TIME_EXCEEDED CODES:
TTL_EXCEEDED = 0
REASSEMBLY_TIME_EXCEEDED = 1
# ECHO REQUEST / ECHO REPLY CODES
ECHO_REQ_REP = 0
# --------------------------





# CODES MAPS
UNREACHABLE_CODES = {
    3 : "PORT_UNREACHABLE",
    2 : "PROTOCOL UNREACHABLE"
}

TIME_EXCEEDED_CODES = {
    0 : "TTL_EXCEEDED",
    1 : "DEFRAGMENTATION_TIME_EXCEEDED"
}