class gaierror(Exception): ...

class ConnectionRefusedError(Exception): ...

# ConnectionResetError: [Errno 104] Connection reset by peer
class ConnectionResetError(Exception): ...

# BrokenPipeError: [Errno 32] Broken pipe
class BrokenPipeError(Exception): ...

# OSError: [Errno 107] Transport endpoint is not connected
